//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIR.SDK.NetStandard.Workflow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIR.SDK.NetStandard.Workflow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnChildWorkflowExecutionFailed.
        /// </summary>
        internal static string OnChildWorkflowExecutionFailed {
            get {
                return ResourceManager.GetString("OnChildWorkflowExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnChildWorkflowExecutionTerminated.
        /// </summary>
        internal static string OnChildWorkflowExecutionTerminated {
            get {
                return ResourceManager.GetString("OnChildWorkflowExecutionTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type Must Be Serializable.
        /// </summary>
        internal static string TheTypeMustBeSerializable {
            get {
                return ResourceManager.GetString("TheTypeMustBeSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Exceeded Maximum Allowed Length.
        /// </summary>
        internal static string ValueExceededMaximumAllowedLength {
            get {
                return ResourceManager.GetString("ValueExceededMaximumAllowedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Must Be Greater Than Or Equal To Zero.
        /// </summary>
        internal static string ValueMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Must Be Less Than 9 Decimal Digits.
        /// </summary>
        internal static string ValueMustBeLessThan9DecimalDigits {
            get {
                return ResourceManager.GetString("ValueMustBeLessThan9DecimalDigits", resourceCulture);
            }
        }
    }
}
